[package]
name = "db-rs"
version = "0.1.0"
edition = "2021"
author = "parth"
description = "fast, embedded, transactional, key value store"
license = "BSD-3-Clause"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"